Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using f1website.Data;
using f1website.Models;

namespace f1website.Controllers
{
    public class CategoriesController : Controller
    {
        private f1WebsiteContext db = new f1WebsiteContext();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using f1website.Data;
using f1website.Models;

namespace f1website.Controllers
{
    public class ResultsController : Controller
    {
        private f1WebsiteContext db = new f1WebsiteContext();

        // GET: Results
        public ActionResult Index(string category, string search)
        {
            var results = db.Results.Include(r => r.Category);
            if (!String.IsNullOrEmpty(search))
            {
                results = results.Where(r => r.Name.Contains(search) || 
                r.Category.Name.Contains(search));
                ViewBag.Search = search;
            }

            var categories = results.OrderBy(p => p.Category.Name).Select(p => p.Category.Name).Distinct();
            if (!String.IsNullOrEmpty(category))
            {
                results = results.Where(r => r.Category.Name == category);
            }
            ViewBag.Category = new SelectList(categories);
            return View(results.ToList());
        }

        // GET: Results/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);

        }

        // GET: Results/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: Results/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Date,Driver1,Driver2,Position1,Position2,CategoryID")] Result result)
        {
            if (ModelState.IsValid)
            {
                db.Results.Add(result);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "Name", result.CategoryID);
            return View(result);
        }

        // GET: Results/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "Name", result.CategoryID);
            return View(result);
        }

        // POST: Results/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Date,Driver1,Driver2,Position1,Position2,CategoryID")] Result result)
        {
            if (ModelState.IsValid)
            {
                db.Entry(result).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "Name", result.CategoryID);
            return View(result);
        }

        // GET: Results/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // POST: Results/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Result result = db.Results.Find(id);
            db.Results.Remove(result);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("F1 Team", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Team", "Team", "Home")</li>
                    <li>@Html.ActionLink("Store", "Store", "Home")</li>
                    <li>@Html.ActionLink("Previous Driver List", "Index", "Categories")</li>
                    <li>@Html.ActionLink("View results", "Index", "Results")</li>
                </ul>
                @using (Html.BeginForm("Index", "Results", FormMethod.Get, new {@class = "navbar-form navbar-right"}))
            {
                <div class="form-group">
                    @Html.TextBox("Search", null, new {@class="form-control", @placeHolder="Search for results"});
                </div>
                <button type="submit" class="btn btn-default">Find Results</button>
            }
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row-no-gutters">
                <div id="footer-credits" class="col-xs-4 col-sm-6">
                    <address>
                        Written by <a href="mailto:lewiskendalljones@gmail.com">Lewis Kendall-Jones</a>
                    </address>
                    <a target="_blank" href="@Url.Action("Copyright", "Home")" class="copyright-acknowledgements">Copyright Acknowledgements</a>
                    @*<hr />
                                  /// Unusable from a local machine.
                    <a target="_blank" href="http://validator.w3.org/check/referer">HTML5 Validation</a>
                    <br />
                    <a target="_blank" href="http://jigsaw.w3.org/css-validator/check/referer">CSS Validation</a>*@
                </div>
                <div id="footer-socials" class="col-xs-4 col-xs-offset-4 col-sm-3 col-sm-offset-3">
                    <div class="row">
                        <div class="col-xs-6"><a href="https://www.snapchat.com" target="_blank"><img src="~/Content/Images/Footer/sc-icon.png" alt="Snapchat Logo (Link)" class="img-responsive" /></a></div>
                        <div class="col-xs-6"><a href="https://www.twitter.com" target="_blank"><img src="~/Content/Images/Footer/tw-icon.png" alt="Twitter Logo (Link)" class="img-responsive" /></a></div>
                        <div class="col-xs-6"><a href="https://www.facebook.com" target="_blank"><img src="~/Content/Images/Footer/fb-icon.png" alt="Facebook Logo (Link)" class="img-responsive" /></a></div>
                        <div class="col-xs-6"><a href="https://www.instagram.com" target="_blank"><img src="~/Content/Images/Footer/ig-icon.png" alt="Instagram Logo (Link)" class="img-responsive" /></a></div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>